data:
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW5laWdoYm9ybHlzdG9yYWdlO0FjY291bnRLZXk9dFFnNEg4TXdqT2M1a3lhdGtGa0x6ZWRvTUZyN0VZN3lleGpTeEhSTDduMXVRZmwvY3hmSzZxNkxIbXVNTTZmU05iZE9Oa2I2UWEyYjhjTEFYc2RWWHc9PTtFbmRwb2ludFN1ZmZpeD1jb3JlLndpbmRvd3MubmV0
  FUNCTIONS_EXTENSION_VERSION: fjM=
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
apiVersion: v1
kind: Secret
metadata:
  name: bcneighborly
---
data:
  host.master: ZWpqdEZWbkQvcWJ2ejVGUnJUcExmM1JPdVJLTS9CZmgzYlZQYmc0T0FrQXZtbzNDeG1FUGlRPT0=
  host.function.default: azROQ3lWMmxGTTAxNU5oZ1hWcTV4VEh3OTBVOEFOVmhHVGg4VWhhSVd1QWQ4eVpONkV6cnpnPT0=
  host.systemKey.default: dzh4eENsbnlOUll4Wnh4Y3ZtUGFEOXJlMlNWQ0F4QTJwdVhQamdvRGVkd3YzQjlGbFN6WnlBPT0=
  functions.createadvertisement.default: eE93N3p1YmFmZ3ZuYXRVdXVQaWlhcmE2RnJxTHNZUGtKSWlTcWxiNlFoT1pTa01WVGNyT2ZRPT0=
  functions.deleteadvertisement.default: M2xTV0pKemc3OEp0c1pUMGxGUWo1RXF6d0ZZYWFFNWkwQmxTZmx1QmE3Nlluc1YvbXl6R2ZRPT0=
  functions.getadvertisement.default: aWF1NkpJbXB2aVNTdTBGY0s5dnQ0MW9pMjRZSW9mUk9od0phRm5SckpMaGFZYTFwTG8xRlNBPT0=
  functions.getadvertisements.default: am54eVlWS2loUFozSHh1dnNYRmloYzBEYUFDZnlXYUtiMnNLeGIwOFZOZDltM2FRMkNuTVJ3PT0=
  functions.getpost.default: MkV4R1VZbUxYSTdmd2RzTUNidzVieGFUUG5WV1hlcnY2Y2J1MkhBcEtEYVBwNjhwUndEenB3PT0=
  functions.getposts.default: d1lXSHBPWnhGckZ5ZVI3SlZyRVBENk9uVUJwV2FIYVVlYUZRcmdOZGNZTEV1UUpESzdYL2pRPT0=
  functions.updateadvertisement.default: RFVZamt3ckpnSVNlZWloMEt6NndZSDEwZGdjS1hjZkVkejJ3ZE1aNUR0SkZYeWhHQmtQMnZnPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-bcneighborly
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bcneighborly-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: bcneighborly-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bcneighborly-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: bcneighborly-http
spec:
  selector:
    app: bcneighborly-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcneighborly-http
  labels:
    app: bcneighborly-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcneighborly-http
  template:
    metadata:
      labels:
        app: bcneighborly-http
    spec:
      containers:
      - name: bcneighborly-http
        image: bcneighborly.azurecr.io/neighborly-api
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-bcneighborly
        envFrom:
        - secretRef:
            name: bcneighborly
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: bcneighborly-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcneighborly
  labels:
    app: bcneighborly
spec:
  selector:
    matchLabels:
      app: bcneighborly
  template:
    metadata:
      labels:
        app: bcneighborly
    spec:
      containers:
      - name: bcneighborly
        image: bcneighborly.azurecr.io/neighborly-api
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: bcneighborly
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: bcneighborly-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bcneighborly
  labels: {}
spec:
  scaleTargetRef:
    name: bcneighborly
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

